### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PixelmonPRO** [superteits/PixelMoney#3]
Hello! Pixelmon crash before the battle. Pixelmon 5.1.0
`java.lang.NoSuchFieldError: controlledPokemon
	at com.teits.pixelmoney.PixelMoney.onBeat(PixelMoney.java:136)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_44_PixelMoney_onBeat_BeatWildPixelmonEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
	at com.pixelmonmod.pixelmon.battles.controller.BattleControllerBase.lambda$checkPokemon$27(BattleControllerBase.java:1073)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.pixelmonmod.pixelmon.battles.controller.BattleControllerBase.checkPokemon(BattleControllerBase.java:1072)
	at com.pixelmonmod.pixelmon.battles.controller.BattleControllerBase.update(BattleControllerBase.java:378)
	at com.pixelmonmod.pixelmon.battles.BattleRegistry.updateBattles(BattleRegistry.java:151)
	at com.pixelmonmod.pixelmon.battles.BattleTickHandler.tickStart(BattleTickHandler.java:12)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_63_BattleTickHandler_tickStart_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by teitss** [comment]
This plugin was developed for PixelMon 5.0.4, 5.1.0 support will be added in the next release
