### ISSUE TITLE
can't find valid economy plugin?

### ISSUE THREAD

**Issue by Willbound** [superteits/PixelMoney#8]
[Server thread/ERROR] [pixelmoney]; PixelMoney didn't found a valid economy plugin. Unloading...
and before that there are other errors saying:
[PixelHunt] Economy not found!
[pixelmoneconomybridge] no economy plugin that implements Economy service found.

not sure what went wrong, and my friend gets this error every time he tries to join
here's his crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
 SpongeCoremod (spongeforge-1.12.2-2768-7.1.6-RC3686.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 7/5/19 2:33 PM
Description: Unexpected error

java.lang.NoSuchMethodError: moze_intel.projecte.api.capabilities.IKnowledgeProvider.getEmc()D
at com.latmod.mods.projectex.client.ProjectEXClientEventHandler.addInfoText(ProjectEXClientEventHandler.java:121)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_52_ProjectEXClientEventHandler_addInfoText_Text.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:696)
at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:717)
at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:173)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by HackuJacku** [comment]
Are you able to provide a list of your mods/plugins using "/sponge mods" and "/sponge plugins"?
